image: node:12.13.1

pipelines:
    custom:
        validate config.json markdown:
            - step:
                caches:
                    - node
                script:
                    - npm install
                    - node ./node_modules/@masterportal/mpconfigparser/cli.js ./doc/config.json.md
        build and test in Browser:
            - step:
                caches:
                    - node
                script:
                    - npm install
                    - apt-get install unzip
                    - ./devtools/scripts/run_browserstack_local.bash
                    - npm run browsertestWithServer
