name: CI

on:
  workflow_dispatch:
  pull_request:
    branches:
      - dev
    paths-ignore:
      - '**.md'
  push:
    branches:
      - dev
    paths-ignore:
      - '**.md'
    

jobs:
  publish:
    runs-on: ubuntu-22.04
    environment: docker.io
    steps:
      - uses: actions/checkout@v3

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Configure build revision
        id: vars
        run: echo "::set-output name=sha_short::${GITHUB_SHA:0:7}"

      - name: Build images
        env:
          REGISTRY_PREFIX: ${{ secrets.DOCKERHUB_USERNAME }}/
          BUILD_REVISION: ${{ steps.vars.outputs.sha_short }}
        run: docker buildx bake --pull
      
      # Publish to Docker Hub
      - name: Push images
        env:
          REGISTRY_PREFIX: ${{ secrets.DOCKERHUB_USERNAME }}/
          BUILD_REVISION: ${{ steps.vars.outputs.sha_short }}
        run: docker buildx bake --push
      
      # Update Docker Hub description
      - name: Docker Hub Description
        uses: peter-evans/dockerhub-description@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
          repository: ${{ github.repository }}
          